In [1]:
#NumPY is one of the most important Linear Algebra Library for Python, it is very fast and is binding to C libraries, NumPY 
#is the main way of using arrays (vetors and matrices) in Python
#To install it if you have Anaconda :    
#  conda install numpy
#  pip install numpy

In [2]:
#defining a NumpyArray
import numpy as np
list = [0,1,2,3,4]
print ('normal form of a list is :{} \nbut an array is the following:'.format(list))
np.array(list)

normal form of a list is :[0, 1, 2, 3, 4] 
but an array is the following:


array([0, 1, 2, 3, 4])

In [3]:
#defining a 2D matrix
matrix= [[1,2],[3,4],[5,6]]
np.array(matrix)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
#np.arange is a common method to define an array in python
np.arange (0,5,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [5]:
#methods : np.zeros / np.ones
print ('1D array:\n{}\n'.format(np.zeros(4)))
print ('2D array:\n {}'.format(np.zeros((3,4))))

1D array:
[0. 0. 0. 0.]

2D array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#np.linespace : to generate an array of values with evenly sapce points 
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [7]:
#np.eye : for creating an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
#np.random... to generate random array in Python 
random = np.random.rand(4,4)
random
#these values are generated based on the uniform distribution from 0 to 1

array([[0.98209437, 0.24167937, 0.23524031, 0.39993425],
       [0.89907131, 0.31181895, 0.26557044, 0.95433205],
       [0.24377865, 0.3298221 , 0.79461748, 0.88478688],
       [0.94144157, 0.55785972, 0.11353696, 0.75126301]])

In [9]:
np.random.randn(4)
#this method generates the values from Gaution distribution centered arround 0

array([-0.31514144, -0.1965184 , -0.1947181 ,  0.22642012])

In [10]:
#reshape method is one of the most usefull methods while working with arrays 
arr= np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
#methods to find the min/max or index location in an array argmax/argmin :
print (random.max())
print (random.min())
print ('the index of the max value is: {}\nthe index of the min values is {}'.format(random.argmax(),random.argmin()))

0.9820943687238953
0.11353695710044254
the index of the max value is: 0
the index of the min values is 14


In [13]:
#dtype is returning the actual data type:
random.dtype

dtype('float64')